# Generated by Django 5.2.17 on 2026-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
